"""add occasion material to garments

Revision ID: 63accb56692f
Revises: a1b2c3d4e5f6
Create Date: 2026-06-16 21:45:00.061043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63accb56692f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wears_garment_id'), table_name='wears')
    op.drop_index(op.f('ix_wears_id'), table_name='wears')
    op.drop_index(op.f('ix_wears_outfit_id'), table_name='wears')
    op.drop_index(op.f('ix_wears_user_id'), table_name='wears')
    op.drop_table('wears')
    op.drop_index(op.f('ix_washes_garment_id'), table_name='washes')
    op.drop_index(op.f('ix_washes_id'), table_name='washes')
    op.drop_index(op.f('ix_washes_user_id'), table_name='washes')
    op.drop_table('washes')
    op.add_column('garments', sa.Column('occasion', sa.String(length=50), nullable=True))
    op.add_column('garments', sa.Column('material', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments', 'material')
    op.drop_column('garments', 'occasion')
    op.create_table('washes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('garment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('washed_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], name=op.f('washes_garment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('washes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('washes_pkey'))
    )
    op.create_index(op.f('ix_washes_user_id'), 'washes', ['user_id'], unique=False)
    op.create_index(op.f('ix_washes_id'), 'washes', ['id'], unique=False)
    op.create_index(op.f('ix_washes_garment_id'), 'washes', ['garment_id'], unique=False)
    op.create_table('wears',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('garment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worn_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], name=op.f('wears_garment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('wears_outfit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wears_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wears_pkey'))
    )
    op.create_index(op.f('ix_wears_user_id'), 'wears', ['user_id'], unique=False)
    op.create_index(op.f('ix_wears_outfit_id'), 'wears', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_wears_id'), 'wears', ['id'], unique=False)
    op.create_index(op.f('ix_wears_garment_id'), 'wears', ['garment_id'], unique=False)
    # ### end Alembic commands ###
