"""create core wardrobe tables

Revision ID: 74c8b52c2e22
Revises: 
Create Date: 2026-06-08 12:51:20.485310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c8b52c2e22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('garments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garments_id'), 'garments', ['id'], unique=False)
    op.create_index(op.f('ix_garments_user_id'), 'garments', ['user_id'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('outfit_garments',
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outfit_id', 'garment_id')
    )
    op.create_table('washes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('washed_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_washes_garment_id'), 'washes', ['garment_id'], unique=False)
    op.create_index(op.f('ix_washes_id'), 'washes', ['id'], unique=False)
    op.create_index(op.f('ix_washes_user_id'), 'washes', ['user_id'], unique=False)
    op.create_table('wears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('garment_id', sa.Integer(), nullable=True),
    sa.Column('worn_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wears_garment_id'), 'wears', ['garment_id'], unique=False)
    op.create_index(op.f('ix_wears_id'), 'wears', ['id'], unique=False)
    op.create_index(op.f('ix_wears_outfit_id'), 'wears', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_wears_user_id'), 'wears', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wears_user_id'), table_name='wears')
    op.drop_index(op.f('ix_wears_outfit_id'), table_name='wears')
    op.drop_index(op.f('ix_wears_id'), table_name='wears')
    op.drop_index(op.f('ix_wears_garment_id'), table_name='wears')
    op.drop_table('wears')
    op.drop_index(op.f('ix_washes_user_id'), table_name='washes')
    op.drop_index(op.f('ix_washes_id'), table_name='washes')
    op.drop_index(op.f('ix_washes_garment_id'), table_name='washes')
    op.drop_table('washes')
    op.drop_table('outfit_garments')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_garments_user_id'), table_name='garments')
    op.drop_index(op.f('ix_garments_id'), table_name='garments')
    op.drop_table('garments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
